# Generated by Django 6.0.7 on 2026-08-05 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_vehicle_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='color',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='price_per_day',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='daily_price',
            field=models.DecimalField(decimal_places=2, default=700, max_digits=8),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='hourly_price',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=8),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='own_rent_price',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=8),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Booked', 'Booked'), ('Maintenance', 'Under Maintenance'), ('Reserved', 'Reserved'), ('Out', 'Out of Service')], default='Available', max_length=20),
        ),
    ]
