# Generated by Django 6.0.3 on 2026-08-11 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_vehicle_model_cart_cartitem_order_orderitem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicledocument',
            name='fitness_document',
        ),
    ]
