# Generated by Django 6.0.3 on 2026-08-11 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_vehicledocument_fitness_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='hours',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
