# Generated by Django 6.0.7 on 2026-08-12 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_cartitem_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='hours',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
